package main

import (
	"bytes"
	"encoding/json"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// Prometheus metric definitions (counters, histograms, gauges)
var (
	promptTokens = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ollama_prompt_tokens_total",
			Help: "Total number of prompt tokens sent to the model",
		},
		[]string{"model"},
	)
	generatedTokens = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ollama_generated_tokens_total",
			Help: "Total number of tokens generated by the model",
		},
		[]string{"model"},
	)
	requestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name: "ollama_request_duration_seconds",
			Help: "Duration of Ollama requests in seconds",
			// Buckets for 0.1s to 60s
			Buckets: []float64{0.1, 0.5, 1, 2, 5, 10, 30, 60},
		},
		[]string{"endpoint", "model"},
	)
	timePerToken = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "ollama_time_per_token_seconds",
			Help:    "Time per generated token (seconds per token)",
			Buckets: []float64{0.01, 0.05, 0.1, 0.2, 0.5, 1, 2},
		},
		[]string{"model"},
	)
	loadedModelsGauge = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "ollama_loaded_models",
			Help: "Number of models currently loaded in memory in Ollama",
		},
	)
	loadedModelInfo = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "ollama_model_loaded",
			Help: "Indicator (1/0) if a model is loaded in memory",
		},
		[]string{"model"},
	)
	modelRAMUsage = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "ollama_model_ram_mb",
			Help: "RAM usage in megabytes for each loaded model",
		},
		[]string{"model"},
	)
)

func init() {
	// Register metrics with Prometheus default registry
	prometheus.MustRegister(promptTokens, generatedTokens, requestDuration, timePerToken, loadedModelsGauge, loadedModelInfo, modelRAMUsage)
}

// Structs to parse JSON responses from Ollama
type generateResponse struct {
	Model              string      `json:"model"`
	Done               *bool       `json:"done,omitempty"`
	Response           string      `json:"response,omitempty"`
	PromptEvalCount    *int        `json:"prompt_eval_count,omitempty"`
	EvalCount          *int        `json:"eval_count,omitempty"`
	TotalDuration      *int64      `json:"total_duration,omitempty"`
	EvalDuration       *int64      `json:"eval_duration,omitempty"`
	PromptEvalDuration *int64      `json:"prompt_eval_duration,omitempty"`
	DoneReason         interface{} `json:"done_reason,omitempty"`
}

type psResponse struct {
	Models []struct {
		Name      string `json:"name"`
		ID        string `json:"id"`
		Size      int64  `json:"size"`      // Size in bytes
		Processor string `json:"processor"`
		Until     string `json:"until"`
	} `json:"models"`
}

type modelsResponse struct {
	Models []struct {
		Name    string `json:"name"`
		Model   string `json:"model"`
		Size    int64  `json:"size"`
		Digest  string `json:"digest"`
		Details struct {
			ParentModel       string   `json:"parent_model"`
			Format            string   `json:"format"`
			Family            string   `json:"family"`
			Families          []string `json:"families"`
			ParameterSize     string   `json:"parameter_size"`
			QuantizationLevel string   `json:"quantization_level"`
		} `json:"details"`
		ExpiresAt string `json:"expires_at"`
		SizeVRAM  int64  `json:"size_vram"`
	} `json:"models"`
}

var upstreamClient = &http.Client{
	// No global timeout; model inference may take a long time
	Timeout: 0,
}

// fixDoneReason processes JSON data to handle the done_reason field that might be a number or string
func fixDoneReason(data []byte) []byte {
	re := regexp.MustCompile(`"done_reason":(\d+)`)
	return re.ReplaceAll(data, []byte(`"done_reason":"$1"`))
}

// ensureModelTag adds ":latest" to model names that don't have a tag
func ensureModelTag(modelName string) string {
	if modelName == "" {
		return modelName
	}
	if !strings.Contains(modelName, ":") {
		return modelName + ":latest"
	}
	return modelName
}

func main() {
	// Configure upstream Ollama host and local port from environment
	upstreamAddr := os.Getenv("OLLAMA_HOST")
	if upstreamAddr == "" {
		upstreamAddr = "http://localhost:11434"
	}
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Starting Ollama proxy sidecar, forwarding to %s", upstreamAddr)

	// Optionally, initialize the loaded models gauge at startup
	if resp, err := upstreamClient.Get(upstreamAddr + "/api/ps"); err == nil {
		var ps psResponse
		data, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		if jsonErr := json.Unmarshal(data, &ps); jsonErr == nil {
			loadedModelsGauge.Set(float64(len(ps.Models)))
			loadedModelInfo.Reset()
			for _, m := range ps.Models {
				loadedModelInfo.WithLabelValues(ensureModelTag(m.Name)).Set(1)
			}
		}
	}

	// Set up HTTP handlers
	mux := http.NewServeMux()
	
	// Custom metrics handler that refreshes model data before serving metrics
	mux.HandleFunc("/metrics", func(w http.ResponseWriter, r *http.Request) {
		// Refresh model information from /api/ps before serving metrics
		if resp, err := upstreamClient.Get(upstreamAddr + "/api/ps"); err == nil {
			var ps psResponse
			data, _ := io.ReadAll(resp.Body)
			resp.Body.Close()
			if jsonErr := json.Unmarshal(data, &ps); jsonErr == nil {
				loadedModelsGauge.Set(float64(len(ps.Models)))
				loadedModelInfo.Reset()
				modelRAMUsage.Reset() // Reset RAM usage before updating
				
				// Update model metrics directly from ps response
				for _, m := range ps.Models {
					modelName := ensureModelTag(m.Name)
					loadedModelInfo.WithLabelValues(modelName).Set(1)
					
					// Convert size from bytes to megabytes
					ramMB := float64(m.Size) / (1024 * 1024)
					modelRAMUsage.WithLabelValues(modelName).Set(ramMB)
				}
				log.Printf("Refreshed metrics data: %d models loaded", len(ps.Models))
			} else {
				log.Printf("ERROR parsing /api/ps response during metrics refresh: %v", jsonErr)
			}
		} else {
			log.Printf("ERROR refreshing model metrics: %v", err)
		}
		
		// Serve metrics using the standard Prometheus handler
		promhttp.Handler().ServeHTTP(w, r)
	})
	
	// All other paths -> proxy handler
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		if r.URL.Path == "/metrics" {
			// Should be handled above; just in case
			promhttp.Handler().ServeHTTP(w, r)
			return
		}

		// Read request body (if any) for forwarding and possibly to inspect model parameter
		var bodyBytes []byte
		if r.Body != nil {
			bodyBytes, _ = io.ReadAll(r.Body)
			r.Body.Close()
		}

		// Build upstream request
		targetURL := upstreamAddr + r.URL.Path
		if r.URL.RawQuery != "" {
			targetURL += "?" + r.URL.RawQuery
		}
		reqUp, err := http.NewRequest(r.Method, targetURL, bytes.NewReader(bodyBytes))
		if err != nil {
			http.Error(w, "Bad request", http.StatusInternalServerError)
			log.Printf("ERROR creating upstream request: %v", err)
			return
		}
		// Copy original headers
		for name, vals := range r.Header {
			if name == "Host" {
				continue // skip Host header
			}
			for _, v := range vals {
				reqUp.Header.Add(name, v)
			}
		}
		if reqUp.Header.Get("Content-Type") == "" && len(bodyBytes) > 0 {
			reqUp.Header.Set("Content-Type", "application/json")
		}

		respUp, err := upstreamClient.Do(reqUp)
		if err != nil {
			http.Error(w, "Upstream error", http.StatusBadGateway)
			log.Printf("ERROR forwarding to upstream: %v", err)
			return
		}
		defer respUp.Body.Close()

		// Forward status code and headers (except hop-by-hop headers)
		for name, vals := range respUp.Header {
			switch strings.ToLower(name) {
			case "transfer-encoding", "content-length":
				continue
			}
			for _, v := range vals {
				w.Header().Add(name, v)
			}
		}
		w.WriteHeader(respUp.StatusCode)

		// Variables for metrics/logging
		var modelName string
		var promptCount, generatedCount int
		var evalDurationNs int64

		if r.URL.Path == "/api/generate" || r.URL.Path == "/api/chat" {
			// Handle streaming JSON response for generate/chat
			var buf bytes.Buffer
			// MultiWriter to write to client output and buffer simultaneously
			streamWriter := io.MultiWriter(w, &buf)
			flusher, _ := w.(http.Flusher)
			// Stream copy loop
			chunk := make([]byte, 1024)
			for {
				n, readErr := respUp.Body.Read(chunk)
				if n > 0 {
					// Write chunk to both client and buffer
					if _, writeErr := streamWriter.Write(chunk[:n]); writeErr != nil {
						log.Printf("WARNING: client write error: %v", writeErr)
						break
					}
					if flusher != nil {
						flusher.Flush() // flush chunk to client
					}
				}
				if readErr != nil {
					// Break on EOF or error
					if readErr != io.EOF {
						log.Printf("ERROR reading upstream: %v", readErr)
					}
					break
				}
			}

			// Fix the JSON before parsing
			bufData := fixDoneReason(buf.Bytes())

			// First, try to parse as models list response
			var modelsResp modelsResponse
			if err := json.Unmarshal(bufData, &modelsResp); err == nil && len(modelsResp.Models) > 0 {
				// This is a models list response, not a typical generate response
				for _, model := range modelsResp.Models {
					modelName = ensureModelTag(model.Model)
					modelRAMUsage.WithLabelValues(modelName).Set(float64(model.SizeVRAM) / (1024 * 1024))
				}
				log.Printf("Received models list response with %d models", len(modelsResp.Models))
				// No token counts for models list response
			} else {
				// Parse lines of JSON objects as standard generate responses
				for _, line := range bytes.Split(bufData, []byte{'\n'}) {
					if len(line) == 0 {
						continue
					}

					var res generateResponse
					if err := json.Unmarshal(line, &res); err != nil {
						log.Printf("WARNING: Failed to parse JSON: %v", err)
						continue
					}

					if res.Model != "" {
						modelName = ensureModelTag(res.Model)
					}

					// If this chunk signals done, capture metrics fields
					if res.Done != nil && *res.Done {
						if res.PromptEvalCount != nil {
							promptCount = *res.PromptEvalCount
						}
						if res.EvalCount != nil {
							generatedCount = *res.EvalCount
						}
						if res.EvalDuration != nil {
							evalDurationNs = *res.EvalDuration
						}
					}
				}
			}
		} else if r.URL.Path == "/api/ps" {
			// Intercept /api/ps to update loaded models metrics
			bodyData, _ := io.ReadAll(respUp.Body)
			w.Write(bodyData) // write response to client
			var ps psResponse
			if err := json.Unmarshal(bodyData, &ps); err == nil {
				loadedModelsGauge.Set(float64(len(ps.Models)))
				loadedModelInfo.Reset()
				modelRAMUsage.Reset() // Reset RAM usage before updating
				
				// Update model metrics directly from ps response
				for _, m := range ps.Models {
					modelName := ensureModelTag(m.Name)
					loadedModelInfo.WithLabelValues(modelName).Set(1)
					
						// Convert size from bytes to megabytes
					ramMB := float64(m.Size) / (1024 * 1024)
					modelRAMUsage.WithLabelValues(modelName).Set(ramMB)
					log.Printf("Model %s RAM usage: %.2f MB", modelName, ramMB)
				}
			} else {
				log.Printf("ERROR parsing /api/ps response: %v", err)
			}
			// We can return here since request is fully handled
			return
		} else {
			// Other endpoints (e.g. /api/tags, /api/pull) - just copy through
			io.Copy(w, respUp.Body)
			// Try to get model name from request (if JSON body has "model")
			if len(bodyBytes) > 0 {
				var reqJson map[string]interface{}
				if err := json.Unmarshal(bodyBytes, &reqJson); err == nil {
					if m, ok := reqJson["model"].(string); ok {
						modelName = ensureModelTag(m)
					}
				}
			}
			// No token metrics for non-generate endpoints
		}

		// Update Prometheus metrics if applicable
		if modelName != "" {
			if promptCount > 0 {
				promptTokens.WithLabelValues(modelName).Add(float64(promptCount))
			}
			if generatedCount > 0 {
				generatedTokens.WithLabelValues(modelName).Add(float64(generatedCount))
			}
			durationSec := time.Since(start).Seconds()
			endpoint := strings.TrimPrefix(r.URL.Path, "/api/")
			if endpoint == "" {
				endpoint = r.URL.Path
			}
			requestDuration.WithLabelValues(endpoint, modelName).Observe(durationSec)
			if generatedCount > 0 && evalDurationNs > 0 {
				// evalDurationNs is in nanoseconds
				secondsPerToken := float64(evalDurationNs) / 1e9 / float64(generatedCount)
				timePerToken.WithLabelValues(modelName).Observe(secondsPerToken)
			}
			// Removed the redundant /api/ps call for /api/generate and /api/chat endpoints
			// Model metrics are now refreshed on every /metrics request
		}

		// Logging
		duration := time.Since(start).Seconds()
		if modelName != "" && (promptCount > 0 || generatedCount > 0) {
			log.Printf("%s %s -> model=%s prompt_tokens=%d generated_tokens=%d duration=%.2fs",
				r.Method, r.URL.Path, modelName, promptCount, generatedCount, duration)
		} else {
			log.Printf("%s %s -> status=%d duration=%.2fs", r.Method, r.URL.Path, respUp.StatusCode, duration)
		}
	})

	// Start HTTP server
	listenAddr := ":" + port
	log.Printf("Listening on %s", listenAddr)
	log.Fatal(http.ListenAndServe(listenAddr, mux))
}
